train_dataset_dir: "check_your_heuristic/resources/TERRa/train.jsonl"
valid_dataset_dir: "check_your_heuristic/resources/TERRa/val.jsonl"
column_name1: "hypothesis"
column_name2: "premise"
target_name: "label"